name: Auto-Checks
on:
  pull_request:
    branches: [ "main" ]

jobs:
  basic-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # 1) Enforce branch naming: must start with the student's GitHub username
      - name: Ensure branch naming (username prefix)
        run: |
          BRANCH="${{ github.head_ref }}"
          USER="${{ github.actor }}"
          echo "Branch: $BRANCH / Actor: $USER"
          if ! echo "$BRANCH" | grep -E "^${USER}/"; then
            echo "Branch must start with your GitHub username: ${USER}/"; exit 1; fi

      # 2) Commit message quality + must reference an issue number
      - name: Check commit messages + issue refs
        run: |
          git log origin/main..HEAD --pretty=format:'%s' -n 50 | tee commits.txt
          if ! grep -E '^(feat|fix|docs|chore|refactor|test|style|perf|setup)(\(.+\))?: ' commits.txt; then
            echo "Use conventional commits (e.g., feat: message)"; exit 1; fi
          if ! grep -E '#[0-9]+' commits.txt; then
            echo "Reference an issue number like (#1) in at least one commit"; exit 1; fi

      # 3) Locate THIS PR's bio file (kept from your original)
      - name: Locate bio file for this PR
        id: bio
        shell: bash
        run: |
          set -euo pipefail
          USER="${{ github.actor }}"
          BASE="${{ github.event.pull_request.base.sha }}"
          HEAD="${{ github.event.pull_request.head.sha }}"

          # 1) Bio files added/modified in THIS PR
          mapfile -t changed < <(git diff --name-only --diff-filter=AM "$BASE".."$HEAD" -- 'students/*-bio.md' || true)

          pick=""
          if (( ${#changed[@]} == 1 )); then
            pick="${changed[0]}"
          elif (( ${#changed[@]} > 1 )); then
            # Prefer the one that mentions @username
            for f in "${changed[@]}"; do
              if grep -qF "@${USER}" "$f"; then pick="$f"; break; fi
            done
            [[ -z "$pick" ]] && pick="${changed[0]}"
          fi

          # 2) Fallback: search any existing bio that mentions @username
          if [[ -z "$pick" ]]; then
            pick="$(grep -rlF "@${USER}" students/*-bio.md 2>/dev/null | head -n1 || true)"
          fi

          if [[ -z "$pick" ]]; then
            echo "Could not determine your bio file. Make sure you added students/<lastname>-bio.md and included your @${USER}" >&2
            exit 1
          fi

          echo "bio_file=$pick" >> "$GITHUB_OUTPUT"
          echo "Found bio: $pick"

      # 4) NEW: Find exactly one group contributors file changed at repo root
      - name: Locate group contributors file (root-level)
        id: grp
        shell: bash
        run: |
          set -euo pipefail
          BASE="${{ github.event.pull_request.base.sha }}"
          HEAD="${{ github.event.pull_request.head.sha }}"

          # Consider only root files matching G<number>-CONTRIBUTORS.md
          mapfile -t gfiles < <(git diff --name-only --diff-filter=AM "$BASE".."$HEAD" -- '*-CONTRIBUTORS.md' \
                                | grep -E '^G[0-9]+-CONTRIBUTORS\.md$' || true)

          if (( ${#gfiles[@]} == 0 )); then
            echo "No group contributors file changed. Edit your group file (e.g., G1-CONTRIBUTORS.md) at the repo root." >&2
            exit 1
          fi
          if (( ${#gfiles[@]} > 1 )); then
            printf "Multiple group contributor files changed:\n%s\n" "${gfiles[@]}" >&2
            echo "Change exactly ONE group file." >&2
            exit 1
          fi

          FILE="${gfiles[0]}"
          echo "file=$FILE" >> "$GITHUB_OUTPUT"
          echo "group_file=$FILE" >> "$GITHUB_OUTPUT"
          echo "Found group file: $FILE"

      # 5) Verify PR author's @username appears in that group file (bullet line)
        - name: Verify @username present in group contributors file
          shell: bash
          run: |
            set -euo pipefail
            USER="${{ github.actor }}"
            FILE="${{ steps.grp.outputs.group_file }}"
            echo "Checking $FILE for @${USER}"

            # Accept -, *, or + bullets, any spaces, then @username
            # After the username, require a non-username char or EOL (prevents partial matches)
            if ! grep -En "^[-*+][[:space:]]+@${USER}([^A-Za-z0-9-]|$)" "$FILE" >/dev/null; then
              echo "❌ Couldn't find a bullet line with @${USER} in $FILE" >&2
              echo "Add a line like:" >&2
              echo "- @${USER} — Your Name (Section: IT342-G0x)" >&2

              echo "— Debug: showing lines that look like bullets with @ handles —"
              grep -En "^[-*+][[:space:]]+@" "$FILE" || true
              exit 1
            fi

            echo "✅ Found bullet line with @${USER} in $FILE"


      # 6) (Optional) Ensure only minimal additions were made to that group file
      - name: Ensure only one new roster line added (optional)
        shell: bash
        run: |
          set -euo pipefail
          BASE="${{ github.event.pull_request.base.sha }}"
          HEAD="${{ github.event.pull_request.head.sha }}"
          FILE="${{ steps.grp.outputs.group_file }}"
          ADDED=$(git diff --unified=0 "$BASE".."$HEAD" -- "$FILE" \
                  | grep -E '^\+' | grep -vE '^\+\+\+ ' | wc -l || true)
          if [ "$ADDED" -gt 3 ]; then
            echo "Too many additions in $FILE. Add only your single roster line." >&2
            exit 1
          fi
          echo "ℹ️ Added lines in $FILE: $ADDED"

      # 7) Bio file must include the student's @username (kept from original)
      - name: Verify @username present in bio
        run: |
          USER="${{ github.actor }}"
          BIO_FILE="${{ steps.bio.outputs.bio_file }}"
          if ! grep -F "@${USER}" "$BIO_FILE" >/dev/null; then
            echo "Your GitHub username (@${USER}) must appear in $BIO_FILE"; exit 1; fi
